stages:
    - build
    - test

build:
    stage: build
    image: python:3.8-alpine
    script: 
        - echo "Building"
        - pip3 install --upgrade pip
        - pip3 install -r requirements.txt

test:
    stage: test
    image: python:3.8-alpine
    script:
        - echo "Testing"
        - pip3 install -r requirements.txt
        - coverage run --source=app --branch -m unittest test/pyunittest.py
        - coverage report -m
        - coverage html -d coverage_reports
    artifacts:
        paths:
        - coverage_reports/
